---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
          - prettier-plugin-sort-json

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.3.1
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args:
          - --exit-non-zero-on-fix

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.12.0
    hooks:
      - id: cspell
        name: Spell check with cspell

  - repo: https://github.com/jsh9/pydoclint
    rev: "0.5.6"
    hooks:
      - id: pydoclint
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pycqa/pylint.git
    rev: v3.2.6
    hooks:
      - id: pylint
        args:
          - --output-format=colorized
        additional_dependencies:
          - pytest
          - tox
          - ansible-lint>=6.22.1
          - GitPython

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
          - tox
        args:
          - src
          - tests
          - --python-version=3.11
        pass_filenames: false
